apiVersion: v1
entries:
  cassandra:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-01-24T21:48:28.647397537+01:00"
    description: A Helm chart for creating Cassandra clusters using the Cassandra
      operator
    digest: 2cf1ee98bd8c8b55b3a0c004d5b75f6fc4b7e940b15a01cc932dbac2b9952884
    home: https://www.instaclustr.com
    keywords:
    - operator
    - cassandra-operator
    - instaclustr
    maintainers:
    - name: Stefan Miklosovic
    - name: Alex Lourie
    - name: Ben Bromhead
    - name: Adam Zegelin
    name: cassandra
    sources:
    - https://github.com/instaclustr/cassandra-operator
    urls:
    - cassandra-1.0.0.tgz
    version: 1.0.0
  cassandra-operator:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-01-24T21:48:28.648296511+01:00"
    description: A Helm chart for Cassandra Operator for Kubernetes by Instaclustr
    digest: c1f567febb226ab0a802da6c7e171adc9882eb3e5e1b4baa1b3bdcd6389cc840
    home: https://www.instaclustr.com
    keywords:
    - operator
    - cassandra-operator
    - instaclustr
    maintainers:
    - name: Stefan Miklosovic
    - name: Alex Lourie
    - name: Ben Bromhead
    - name: Adam Zegelin
    name: cassandra-operator
    sources:
    - https://github.com/instaclustr/cassandra-operator
    urls:
    - cassandra-operator-1.0.0.tgz
    version: 1.0.0
generated: "2020-01-24T21:48:28.644333434+01:00"
